### ISSUE TITLE
画像をClientからApiに渡して保存する方法

### ISSUE THREAD

**Issue by junjungoal** [tc-geeks/api#1]

**Comment by junjungoal** [comment]
Client 側でBase64にエンコードしてApi側でdecodeして保存する。

```
def decode_base64_image
    if params[:main_image]
      main_image = params[:main_image]
      decode_data = Base64.decode64(main_image[:image_data])
      data = StringIO.new(decode_data)
      data.class_eval do
        attr_accessor :content_type, :original_filename
      end
      data.content_type = main_image[:content_type]
      data.original_filename = File.basename(main_image[:original_filename])
      params[:main_image] = data
    end
  end
```

**Comment by junjungoal** [comment]
これ別の解決策ありそうなのでpendding
分かり次第commentします。

**Comment by sainu** [comment]
まじ？
神、待ってる
![](http://lgtm.in/p/2lSzj7vOp)

**Comment by junjungoal** [comment]
まず、基本的なところから入るけど、POSTでのデータの送信の方法は4つくらいあって、今回メインで考えなければならないのは、URLエンコードでPOSTする方法と、multipart形式でのPOSTの方法の2つ。
参考: http://wagavulin.hatenablog.com/entry/2015/10/18/060938

基本的に画像データを送信する必要がない場合はURLエンコードの形でリクエストを飛ばすのが好ましい。railsではfile_fieldとかがないと自動でURLエンコードでのPOSTでやってくれる。このどのような方法でPOSTをするかはrequestのheaderの`CONTENT-TYPE`というので判断してくれていて、URLエンコード形式の場合は、

```
request.headers["CONTENT-TYPE"]  #=>  application/x-www-form-urulencoded
```

となる。

では画像データを送る場合はどうなるかというと、この場合はmultipart形式で送るのが好ましい。multipart形式というのは形式というのはネスト?している情報をおくることができるため、画像のデータやファイルを送るのに好ましい。
この場合もheaderのCONTENT-TYPEで判断し、中身は`multipart/form-data`というタイプになる。

multipart形式で情報を送る場合、どのようにデータが送られるかというと、

```
POST test.php HTTP/1.1\r\n
Host: satoxpochi.com\r\n
Content-Type: multipart/form-data; boundary=---------------------------102852708831426\r\n
Content-Length: 「ボディ部のサイズ」\r\n
\r\n
-----------------------------102852708831426\r\n
Content-Disposition: form-data; name="password"\r\n
\r\n
ponpoko\r\n
-----------------------------102852708831426\r\n
Content-Disposition: form-data; name="level"\r\n
\r\n
high\r\n
-----------------------------102852708831426\r\n
Content-Disposition: form-data; name="filename"; filename="text.txt"\r\n
Content-Type: application/octet-stream\r\n
Content-Transfer-Encoding: binary\r\n
\r\n
abcd
-----------------------------102852708831426--\r\n

```

こんな感じで、Content-Dispositionにファイルの名前、その下にファイルの情報が入るようになる。(ここは別途勉強が必要)

で、問題はおれをどのようにrubyで表現するかで、実はrubyのライブラリーが古いのかなんかでmaltipart形式がサポートされていない...という問題が有ります。基本的にURLエンコード形式で情報が送信されるので、うまく行きません。

なので方法は２つあります。
- 上記のmaltipart形式のbodyの中身を自分でつくる。

参考URL: http://mymo.blog8.fc2.com/blog-entry-15.html
このブログに書いてあるのですが、concatメソッドを使って頑張って書いていく。

ただ流石にこれだとprimitive過ぎて大変なので、良い方法として以下が有ります。
- formから送られてくるリクエストのbodyをそのまま使う

htmlのformから送られてくる情報は、newアクションからcreateアクションに対して画像データが存在した場合、multipart形式で送られてくるので、すでにbodyは上記のmultipart形式の形ができている状態にある。そのためこれをこれを利用してapiを叩けばよい。具体的なコードはこんな感じ。

controllers/users_controller.rb

```
class UsersController < ActionController
  def new
  end

  def  create
    ApiClient::User.create(request)  #このrequestはformから送られてくるrequest。中にheaderやbodyなどの情報が詰まっている。
  end 
```

lib/api_client/connection.rb

```
module ApiClient
  class Connection 
    def initialize(uri)
      @uri = uri
    end

    def post(req)
      res = Net::HTTP.start(@uri.host, @uri.port){|http|
        _req = Net::HTTP::Post.new(@uri.path) 
        _req.set_content_type(req.headers["CONTENT-TYPE"])
        _req.body = req.body.read
        http.request(_req)
      }
      OpenStruct.new(JSON.parse(res.body))
    end
end
```

lib/api_client/base.rb

```
module ApiClient
  class Base

    def self.create(attributes=nil, opt={}, &block)
      connection(__method__).post(attributes)
    end

    def self.find(attributes=nil, opt={}, &block)
      connection(__method__).get(attributes)
    end

    private
    def self.connection(method)
      ApiClient::Connection.new(uri(method))
    end

    def self.uri(method)
      URI.parse Settings.api.url + ApiUri::API_URI_LIST[fetch_class][method]
    end

    def self.fetch_class
      self.name.split('::').last.downcase.to_sym
    end
  end

end

```

lib/api_client/user.rb

```
module ApiClient
  class User < ApiClient::Base
  end
end
```

app/model/api_uri

```
class ApiUri
  API_URI_LIST = {
    user: { find: "users", create: "users},
  }
end
```

いくつか載せましたが基本的に重要なのは users_controllerとconnection.rbで、
usrs_controlerではrequestをそのまま引数で送り、connectionクラス内での

```
      res = Net::HTTP.start(@uri.host, @uri.port){|http|
        _req = Net::HTTP::Post.new(@uri.path) 
        _req.set_content_type(req.headers["CONTENT-TYPE"])
        _req.body = req.body.read
        http.request(_req)
      }
      OpenStruct.new(JSON.parse(res.body))

```

ここでrequestを分解し、 formから送られてきたbodyを`_req = Net::HTTP::Post.new(@uri.path)`のインスタンスのbodyという変数の中にぶち込みます。

```
  _req.body = req.body.read
```

この際気をつけなければならないのは、req.bodyはStringIO型で取れてしまうのでreadしてバイナリを取得しなければなりません。

あとはこれを用いて`http.request`してあげればうまくapi側に画像データを送信することができます。

**Comment by junjungoal** [comment]
何かあればぜひ聞いてください！　一旦close
